apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartfreelance-deployment
spec:
  replicas: 1

  # ✅ FIX: prevents rollout stuck issue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: smartfreelance

  template:
    metadata:
      labels:
        app: smartfreelance

    spec:

      initContainers:
        - name: wait-for-mysql
          image: mysql:8.0
          command:
            - sh
            - -c
            - >
              until mysqladmin ping -h smartfreelance-mysql -uroot -proot --silent;
              do sleep 3; done;

      containers:
        - name: smartfreelance
          image: nassimrafrafi/smartfreelance:latest
          ports:
            - containerPort: 8083

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://smartfreelance-mysql:3306/pi_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

          # ✅ IMPORTANT FIX
          terminationGracePeriodSeconds: 10
