apiVersion: v1
kind: Secret
metadata:
  name: application-contract-service-secret
  labels:
    app: application-contract-service
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: ""