pipeline {
  agent any

  stages {
    stage("Checkout") {
      steps {
        checkout scm
      }
    }

    stage("Set Java 17") {
      steps {
        sh """
          export JAVA_HOME=\$(dirname \$(dirname \$(readlink -f \$(which javac))))
          java -version
          mvn -version
        """
      }
    }

    stage("Build & Test") {
      steps {
        dir("smartfreelance-backend/user-service") {
          sh "mvn -B clean verify"
        }
      }
    }

    stage("Archive JaCoCo") {
      steps {
        archiveArtifacts artifacts: "smartfreelance-backend/user-service/target/site/jacoco/**", fingerprint: true, allowEmptyArchive: true
      }
    }
  }
}
